displayName: Sigv4 Auth for AWS
type: middleware

import: github.com/ygormartins/traefikAwsSigv4Middlewarev1

summary: Sign AWS requests using Sigv4

testData:
  accessKey: Q3AM3UQ867SPQQA43P2F
  secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  service: s3
  endpoint: play.min.io
  region: us-east-1
